* Kituu

****  Environment (dotfiles, scripts, binary packages, emacs and Mozilla extensions so far) installation & update sh (tested w/ BASH and ZSH) script

What do one need on a given computer ? Dotfiles ("hidden"
configuration files in your $HOME dir, names start with a dot, hence
the name. It's a big deal. GNU/Linux works like this), a selection of
packages depending on what I intend to do with that rig, and
emacs. AFAIC, that's it. And there's only so many times a guy can type
"install zile", "mkdir ~/tmp", and many bits that get painful to do
and re-do over time.

*NOTA BENE* You can "preview" the script by answering "no" to every
 question, and then get a taste of what would be going on without
 touching anything. The idea here being that you make this system your
 own

*** Features
   -Install and maintain the things I (and you too I guess) need on every machine I install :
     -Binary packages (debian only, sorry. I mean of course I can detect your distro - in the dark - but every single one has its own package naming scheme, what are you gonna do?)
     -Mozilla (Firefox, Thunderbird, ABrowser, whatever) add-ons
     -Various scripts from Version Controlled repositories
   -Manage multiple VC systems
     -GIT
     -SVN
     -BZR
     -CVS
     -Anything that's three-letter named :)
   -Allow editing of the files as well as deployment : It's a big deal and it's the whole point of the thing
   -Setup a home dir the way I'm used to

*** Installation
    -cd ~/
    -git clone https://github.com/xaccrocheur/kituu.git .kituu && .kituu/scripts/kituu-setup.sh

    Or, to install it and be able to modify it and push back your changes to github (if you're me, for instance)

    -git clone git@github.com:xaccrocheur/kituu.git .kituu && .kituu/scripts/kituu-setup.sh -rw
    -Then run *kituu-setup.sh -rw* afterwards to update your packages

**** This will :
    -Clone a repository at ~/.kituu/
    -Backup existing ~/dotfiles as ~/dotfile.orig
    -Symlink ~/.kituu/* in ~/*
      -(Now you have a new dir, ~/script/ and it's in your $PATH)
    -Install a selection of packages, sorted by groups: Multimedia, Dev, Music prod, etc. You're asked for each group if you want to install.
    -Generate a local web page on the fly, where you can install a selection of Mozilla extensions
    -Download, build and install the latest emacs from Savannah trunk
    -Update everything to the latest version at each subsequent run

*** LICENSE
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
