#!/bin/bash

if ps aux | grep $(whoami) | grep 'emacs ' | grep --extended-regexp --invert-match 'grep' &>/dev/null ; then
    emacsclient --no-wait "$@" &
else
    emacs --maximized $@ >/dev/null 2>&1
fi
